# Generated by Django 4.1 on 2022-09-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='제목')),
                ('des', models.CharField(max_length=150, null=True, verbose_name='설명')),
                ('image', models.ImageField(upload_to='project/banner/', verbose_name='배너이미지')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
